; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = board1

[env]
platform = espressif32@^6.5.0
board = pico32
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0

build_flags = 
	-DIMAC
#    -DUBC
#    -DMQTT
    -DESPNOW
    
[env:board1]
build_flags = 
	${env.build_flags}
	-D DEVICE_ID=\"esp32-01\"
	-D IP_ADDR_LAST_OCTET=184
    -D DEBUG=1
    -D TTR=1


#[env:board2]
#build_flags = 
#	${env.build_flags}
#	-D DEVICE_ID=\"esp32-02\"
#	-D IP_ADDR_LAST_OCTET=185
#
#
#[env:board3]
#build_flags = 
#	${env.build_flags}
#	-D DEVICE_ID=\"esp32-03\"
#	-D IP_ADDR_LAST_OCTET=186
#
#
#[env:board4]
#build_flags = 
#	${env.build_flags}
#	-D DEVICE_ID=\"esp32-04\"
#	-D IP_ADDR_LAST_OCTET=187
#
